import {
  Loader2,
  User,
  Mail,
  Lock,
  Chrome,
  MessageSquare,
  Send,
  Paperclip,
  Smile,
  Search,
  Settings,
  LogOut,
  Image,
  ImageOff,
  Video,
  File,
  Camera,
  Download,
  UserPlus,
  UserCheck,
  Users,
  Check,
  X,
  Shield,
  Info,
  CheckCircle,
  Key,
  RefreshCw,
  AlertTriangle,
  Smartphone,
  Copy,
  Wifi,
  Eye
} from "lucide-react"

export const Icons = {
  spinner: Loader2,
  user: User,
  mail: Mail,
  lock: Lock,
  google: Chrome,
  messageSquare: MessageSquare,
  send: Send,
  paperclip: Paperclip,
  smile: Smile,
  search: Search,
  settings: Settings,
  logout: LogOut,
  image: Image,
  imageOff: ImageOff,
  video: Video,
  file: File,
  camera: Camera,
  download: Download,
  userPlus: UserPlus,
  userCheck: UserCheck,
  users: Users,
  check: Check,
  x: X,
  shield: Shield,
  info: Info,
  checkCircle: CheckCircle,
  key: Key,
  refresh: RefreshCw,
  alertTriangle: AlertTriangle,
  smartphone: Smartphone,
  copy: Copy,
  wifi: Wifi,
  eye: Eye
}